name: "Reusable Notification Workflow"
on:
  workflow_call:
    inputs:
      USER_MAPPING:
        type: string
        required: false
    secrets:
      CHATWORK_TOKEN:
        required: true
      CHATWORK_ROOM_ID:
        required: true

jobs:
  notify-chatwork:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install jq

      - name: Notify Chatwork
        env:
          CHATWORK_TOKEN: ${{ secrets.CHATWORK_TOKEN }}
          CHATWORK_ROOM_ID: ${{ secrets.CHATWORK_ROOM_ID }}
          USER_MAPPING: ${{ inputs.USER_MAPPING }}
        run: |
          chmod +x .github/scripts/event_action.sh
          bash .github/scripts/event_action.sh