name: Notify Chatwork on PR Events

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - closed
      - assigned
    branches:
      - main
      - develop
  pull_request_review:
    types:
      - submitted
  pull_request_review_comment:
    types:
      - created
      - edited
  issue_comment:
    types:
      - created
      - edited

jobs:
  call-chatwork-notification:
    # if: >- 
    #   github.event.issue.pull_request == true
    #   || github.event.pull_request.merged == true
    #   || github.event.action == 'opened'
    #   || github.event.action == 'reopened'
    #   || github.event.action == 'edited'
    #   || github.event.action == 'review_requested'
    #   || github.event.action == 'synchronize'
    #   || github.event.action == 'closed'
    #   || github.event.action == 'assigned'
    uses: genepa-yokoyama/workflow-sample/.github/workflows/base-chatwork-notification.yml@main
    secrets:
      CHATWORK_TOKEN: ${{ secrets.CHATWORK_BOT_TOKEN }}
      CHATWORK_ROOM_ID: ${{ secrets.CHATWORK_ROOM_ID }}
    with:
      USER_MAPPING: ${{ vars.CHATWORK_USER_MAPPING }}
